/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
/** biome-ignore-all lint/suspicious/noApproximativeNumericConstant: <ignore> */

import { useGLTF } from "@react-three/drei";
import type { JSX } from "react";
import type * as THREE from "three";
import type { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Object_70: THREE.Mesh;
    Object_74: THREE.Mesh;
    Object_6: THREE.Mesh;
    Object_10: THREE.Mesh;
    Object_14: THREE.Mesh;
    Object_18: THREE.Mesh;
    Object_22: THREE.Mesh;
    Object_26: THREE.Mesh;
    Object_30: THREE.Mesh;
    Object_34: THREE.Mesh;
    Object_38: THREE.Mesh;
    Object_42: THREE.Mesh;
    Object_46: THREE.Mesh;
    Object_50: THREE.Mesh;
    Object_54: THREE.Mesh;
    Object_58: THREE.Mesh;
    Object_62: THREE.Mesh;
    Object_66: THREE.Mesh;
    Object_181: THREE.Mesh;
    Object_182: THREE.Mesh;
    Object_183: THREE.Mesh;
    Object_184: THREE.Mesh;
    Object_185: THREE.Mesh;
    Object_175: THREE.Mesh;
    Object_176: THREE.Mesh;
    Object_177: THREE.Mesh;
    Object_178: THREE.Mesh;
    Object_179: THREE.Mesh;
    Object_187: THREE.Mesh;
    Object_188: THREE.Mesh;
    Object_189: THREE.Mesh;
    Object_190: THREE.Mesh;
    Object_197: THREE.Mesh;
    Object_198: THREE.Mesh;
    Object_199: THREE.Mesh;
    Object_200: THREE.Mesh;
    Object_202: THREE.Mesh;
    Object_203: THREE.Mesh;
    Object_204: THREE.Mesh;
    Object_205: THREE.Mesh;
    Object_212: THREE.Mesh;
    Object_213: THREE.Mesh;
    Object_214: THREE.Mesh;
    Object_215: THREE.Mesh;
    Object_217: THREE.Mesh;
    Object_218: THREE.Mesh;
    Object_219: THREE.Mesh;
    Object_220: THREE.Mesh;
    Object_222: THREE.Mesh;
    Object_223: THREE.Mesh;
    Object_224: THREE.Mesh;
    Object_225: THREE.Mesh;
    Object_227: THREE.Mesh;
    Object_228: THREE.Mesh;
    Object_229: THREE.Mesh;
    Object_230: THREE.Mesh;
    Object_232: THREE.Mesh;
    Object_233: THREE.Mesh;
    Object_234: THREE.Mesh;
    Object_235: THREE.Mesh;
    Object_237: THREE.Mesh;
    Object_238: THREE.Mesh;
    Object_239: THREE.Mesh;
    Object_240: THREE.Mesh;
    Object_242: THREE.Mesh;
    Object_243: THREE.Mesh;
    Object_244: THREE.Mesh;
    Object_245: THREE.Mesh;
    Object_247: THREE.Mesh;
    Object_248: THREE.Mesh;
    Object_249: THREE.Mesh;
    Object_250: THREE.Mesh;
    Object_192: THREE.Mesh;
    Object_193: THREE.Mesh;
    Object_194: THREE.Mesh;
    Object_195: THREE.Mesh;
    Object_76: THREE.Mesh;
    Object_77: THREE.Mesh;
    Object_78: THREE.Mesh;
    Object_79: THREE.Mesh;
    Object_80: THREE.Mesh;
    Object_81: THREE.Mesh;
    Object_89: THREE.Mesh;
    Object_90: THREE.Mesh;
    Object_91: THREE.Mesh;
    Object_92: THREE.Mesh;
    Object_93: THREE.Mesh;
    Object_95: THREE.Mesh;
    Object_96: THREE.Mesh;
    Object_97: THREE.Mesh;
    Object_98: THREE.Mesh;
    Object_99: THREE.Mesh;
    Object_101: THREE.Mesh;
    Object_102: THREE.Mesh;
    Object_103: THREE.Mesh;
    Object_104: THREE.Mesh;
    Object_105: THREE.Mesh;
    Object_83: THREE.Mesh;
    Object_84: THREE.Mesh;
    Object_85: THREE.Mesh;
    Object_86: THREE.Mesh;
    Object_87: THREE.Mesh;
    Object_112: THREE.Mesh;
    Object_113: THREE.Mesh;
    Object_114: THREE.Mesh;
    Object_115: THREE.Mesh;
    Object_117: THREE.Mesh;
    Object_118: THREE.Mesh;
    Object_119: THREE.Mesh;
    Object_120: THREE.Mesh;
    Object_122: THREE.Mesh;
    Object_123: THREE.Mesh;
    Object_124: THREE.Mesh;
    Object_125: THREE.Mesh;
    Object_127: THREE.Mesh;
    Object_128: THREE.Mesh;
    Object_129: THREE.Mesh;
    Object_130: THREE.Mesh;
    Object_132: THREE.Mesh;
    Object_133: THREE.Mesh;
    Object_134: THREE.Mesh;
    Object_135: THREE.Mesh;
    Object_137: THREE.Mesh;
    Object_138: THREE.Mesh;
    Object_139: THREE.Mesh;
    Object_140: THREE.Mesh;
    Object_142: THREE.Mesh;
    Object_143: THREE.Mesh;
    Object_144: THREE.Mesh;
    Object_145: THREE.Mesh;
    Object_107: THREE.Mesh;
    Object_108: THREE.Mesh;
    Object_109: THREE.Mesh;
    Object_110: THREE.Mesh;
    Object_153: THREE.Mesh;
    Object_154: THREE.Mesh;
    Object_155: THREE.Mesh;
    Object_156: THREE.Mesh;
    Object_157: THREE.Mesh;
    Object_159: THREE.Mesh;
    Object_160: THREE.Mesh;
    Object_161: THREE.Mesh;
    Object_162: THREE.Mesh;
    Object_163: THREE.Mesh;
    Object_147: THREE.Mesh;
    Object_148: THREE.Mesh;
    Object_149: THREE.Mesh;
    Object_150: THREE.Mesh;
    Object_151: THREE.Mesh;
    Object_252: THREE.Mesh;
    Object_171: THREE.Mesh;
    Object_172: THREE.Mesh;
    Object_173: THREE.Mesh;
    Object_5: THREE.Mesh;
    Object_6001: THREE.Mesh;
    Object_7: THREE.Mesh;
    Object_10001: THREE.Mesh;
    Object_11: THREE.Mesh;
    Object_9: THREE.Mesh;
    Object_20: THREE.Mesh;
    Object_21: THREE.Mesh;
    Object_13: THREE.Mesh;
    Object_14001: THREE.Mesh;
    Object_15: THREE.Mesh;
    Object_16: THREE.Mesh;
    Object_17: THREE.Mesh;
    Object_18001: THREE.Mesh;
    Object_5001: THREE.Mesh;
    Object_6002: THREE.Mesh;
    Object_7001: THREE.Mesh;
    Object_17001: THREE.Mesh;
    Object_19: THREE.Mesh;
    Object_20001: THREE.Mesh;
    Object_22001: THREE.Mesh;
    Object_10002: THREE.Mesh;
    Object_11001: THREE.Mesh;
    Object_12: THREE.Mesh;
    Object_13001: THREE.Mesh;
    Object_14002: THREE.Mesh;
    Object_15001: THREE.Mesh;
    Object_9001: THREE.Mesh;
  };
  materials: {
    material_0: THREE.MeshStandardMaterial;
    default_white: THREE.MeshStandardMaterial;
    silver_grey: THREE.MeshStandardMaterial;
    lights: THREE.MeshStandardMaterial;
    default_grey: THREE.MeshStandardMaterial;
    default_white_2: THREE.MeshStandardMaterial;
    default_white_3: THREE.MeshStandardMaterial;
    engine_light: THREE.MeshStandardMaterial;
    "default_white_2.001": THREE.MeshStandardMaterial;
    "silver_grey.001": THREE.MeshStandardMaterial;
    "default_grey.001": THREE.MeshStandardMaterial;
    ENGING_light: THREE.MeshStandardMaterial;
    "default_white.001": THREE.MeshStandardMaterial;
    "default_white_3.001": THREE.MeshStandardMaterial;
    "Material.001": THREE.MeshStandardMaterial;
    heat_sheild: THREE.MeshStandardMaterial;
    "default_white_2.002": THREE.MeshStandardMaterial;
    "silver_grey.002": THREE.MeshStandardMaterial;
    "default_grey.002": THREE.MeshStandardMaterial;
    "material_0.001": THREE.MeshStandardMaterial;
    "ENGING_light.001": THREE.MeshStandardMaterial;
    "heat_sheild.002": THREE.MeshStandardMaterial;
    "default_grey.003": THREE.MeshStandardMaterial;
    "Material.002": THREE.MeshStandardMaterial;
    "heat_sheild.001": THREE.MeshStandardMaterial;
    "default_white_3.002": THREE.MeshStandardMaterial;
    very_white: THREE.MeshStandardMaterial;
    "default_white.002": THREE.MeshStandardMaterial;
  };
};

export function EnduranceModel(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/models/endurance.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[0.419, -0.242, -5.931]} rotation={[0, 0, -2.094]}>
        <group rotation={[3.113, 0, 0]}>
          <mesh
            castShadow
            geometry={nodes.Object_70.geometry}
            material={materials.material_0}
            position={[0, 0.653, -5.915]}
            receiveShadow
            rotation={[-3.113, 0, 0]}
          />
        </group>
      </group>
      <group position={[-0.419, -0.242, -5.931]} rotation={[0, 0, 2.094]}>
        <group rotation={[3.113, 0, 0]}>
          <mesh
            castShadow
            geometry={nodes.Object_74.geometry}
            material={materials.material_0}
            position={[0, 0.653, -5.915]}
            receiveShadow
            rotation={[-3.113, 0, 0]}
          />
        </group>
      </group>
      <group position={[-0.539, 0, -5.965]}>
        <group rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh
            castShadow
            geometry={nodes.Object_6.geometry}
            material={materials.material_0}
            position={[-5.965, -0.539, 0]}
            receiveShadow
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          />
        </group>
      </group>
      <group position={[-0.492, -0.219, -5.965]} rotation={[0, 0, 0.419]}>
        <group rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh
            castShadow
            geometry={nodes.Object_10.geometry}
            material={materials.material_0}
            position={[-5.965, -0.539, 0]}
            receiveShadow
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          />
        </group>
      </group>
      <group position={[-0.36, -0.4, -5.96]} rotation={[-0.014, -0.003, 0.837]}>
        <group rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh
            castShadow
            geometry={nodes.Object_14.geometry}
            material={materials.material_0}
            position={[-5.965, -0.539, 0]}
            receiveShadow
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          />
        </group>
      </group>
      <group
        position={[-0.167, -0.512, -5.954]}
        rotation={[-0.026, -0.012, 1.256]}
      >
        <group rotation={[-Math.PI / 2, 0, 1.571]}>
          <mesh
            castShadow
            geometry={nodes.Object_18.geometry}
            material={materials.material_0}
            position={[-5.965, -0.539, 0]}
            receiveShadow
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          />
        </group>
      </group>
      <group
        position={[0.056, -0.535, -5.946]}
        rotation={[-0.033, -0.024, 1.675]}
      >
        <group rotation={[-Math.PI / 2, 0, 1.571]}>
          <mesh
            castShadow
            geometry={nodes.Object_22.geometry}
            material={materials.material_0}
            position={[-5.965, -0.539, 0]}
            receiveShadow
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          />
        </group>
      </group>
      <group
        position={[0.268, -0.466, -5.939]}
        rotation={[-0.035, -0.039, 2.093]}
      >
        <group rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh
            castShadow
            geometry={nodes.Object_26.geometry}
            material={materials.material_0}
            position={[-5.965, -0.539, 0]}
            receiveShadow
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          />
        </group>
      </group>
      <group
        position={[0.434, -0.316, -5.933]}
        rotation={[-0.03, -0.052, 2.512]}
      >
        <group rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh
            castShadow
            geometry={nodes.Object_30.geometry}
            material={materials.material_0}
            position={[-5.965, -0.539, 0]}
            receiveShadow
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          />
        </group>
      </group>
      <group
        position={[0.525, -0.112, -5.93]}
        rotation={[-0.021, -0.063, 2.931]}
      >
        <group rotation={[-Math.PI / 2, 0, 1.571]}>
          <mesh
            castShadow
            geometry={nodes.Object_34.geometry}
            material={materials.material_0}
            position={[-5.965, -0.539, 0]}
            receiveShadow
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          />
        </group>
      </group>
      <group
        position={[0.525, 0.112, -5.93]}
        rotation={[-0.007, -0.069, -2.933]}
      >
        <group rotation={[-Math.PI / 2, 0, 1.571]}>
          <mesh
            castShadow
            geometry={nodes.Object_38.geometry}
            material={materials.material_0}
            position={[-5.965, -0.539, 0]}
            receiveShadow
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          />
        </group>
      </group>
      <group
        position={[0.434, 0.316, -5.933]}
        rotation={[0.007, -0.069, -2.513]}
      >
        <group rotation={[-Math.PI / 2, 0, 1.571]}>
          <mesh
            castShadow
            geometry={nodes.Object_42.geometry}
            material={materials.material_0}
            position={[-5.965, -0.539, 0]}
            receiveShadow
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          />
        </group>
      </group>
      <group
        position={[0.268, 0.466, -5.939]}
        rotation={[0.021, -0.063, -2.093]}
      >
        <group rotation={[-Math.PI / 2, 0, 1.571]}>
          <mesh
            castShadow
            geometry={nodes.Object_46.geometry}
            material={materials.material_0}
            position={[-5.965, -0.539, 0]}
            receiveShadow
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          />
        </group>
      </group>
      <group
        position={[0.055, 0.535, -5.946]}
        rotation={[0.03, -0.052, -1.674]}
      >
        <group rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh
            castShadow
            geometry={nodes.Object_50.geometry}
            material={materials.material_0}
            position={[-5.965, -0.539, 0]}
            receiveShadow
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          />
        </group>
      </group>
      <group
        position={[-0.167, 0.512, -5.954]}
        rotation={[0.035, -0.039, -1.255]}
      >
        <group rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh
            castShadow
            geometry={nodes.Object_54.geometry}
            material={materials.material_0}
            position={[-5.965, -0.539, 0]}
            receiveShadow
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          />
        </group>
      </group>
      <group position={[-0.361, 0.4, -5.96]} rotation={[0.033, -0.024, -0.837]}>
        <group rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh
            castShadow
            geometry={nodes.Object_58.geometry}
            material={materials.material_0}
            position={[-5.965, -0.539, 0]}
            receiveShadow
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          />
        </group>
      </group>
      <group
        position={[-0.492, 0.219, -5.965]}
        rotation={[0.026, -0.012, -0.418]}
      >
        <group rotation={[-Math.PI / 2, 0, Math.PI / 2]}>
          <mesh
            castShadow
            geometry={nodes.Object_62.geometry}
            material={materials.material_0}
            position={[-5.965, -0.539, 0]}
            receiveShadow
            rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          />
        </group>
      </group>
      <group position={[0, 0.484, -5.931]}>
        <group rotation={[3.113, 0, 0]}>
          <mesh
            castShadow
            geometry={nodes.Object_66.geometry}
            material={materials.material_0}
            position={[0, 0.653, -5.915]}
            receiveShadow
            rotation={[-3.113, 0, 0]}
          />
        </group>
      </group>
      <group rotation={[Math.PI / 2, 0, Math.PI / 2]}>
        <mesh
          castShadow
          geometry={nodes.Object_181.geometry}
          material={materials.default_white}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_182.geometry}
          material={materials.silver_grey}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_183.geometry}
          material={materials.lights}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_184.geometry}
          material={materials.default_grey}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_185.geometry}
          material={materials.default_white_2}
          receiveShadow
        />
      </group>
      <group rotation={[Math.PI / 2, 0, Math.PI / 2]}>
        <mesh
          castShadow
          geometry={nodes.Object_175.geometry}
          material={materials.default_white}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_176.geometry}
          material={materials.silver_grey}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_177.geometry}
          material={materials.lights}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_178.geometry}
          material={materials.default_grey}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_179.geometry}
          material={materials.default_white_2}
          receiveShadow
        />
      </group>
      <group rotation={[Math.PI / 2, 0, Math.PI / 2]}>
        <mesh
          castShadow
          geometry={nodes.Object_187.geometry}
          material={materials.default_white}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_188.geometry}
          material={materials.silver_grey}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_189.geometry}
          material={materials.lights}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_190.geometry}
          material={materials.default_white_2}
          receiveShadow
        />
      </group>
      <group rotation={[0, 0, -Math.PI / 6]}>
        <mesh
          castShadow
          geometry={nodes.Object_197.geometry}
          material={materials.default_white}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_198.geometry}
          material={materials.lights}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_199.geometry}
          material={materials.default_grey}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_200.geometry}
          material={materials.default_white_2}
          receiveShadow
        />
      </group>
      <group rotation={[0, 0, -Math.PI]}>
        <mesh
          castShadow
          geometry={nodes.Object_202.geometry}
          material={materials.default_white}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_203.geometry}
          material={materials.lights}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_204.geometry}
          material={materials.default_grey}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_205.geometry}
          material={materials.default_white_2}
          receiveShadow
        />
      </group>
      <group rotation={[0, 0, -Math.PI / 3]}>
        <mesh
          castShadow
          geometry={nodes.Object_212.geometry}
          material={materials.default_white}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_213.geometry}
          material={materials.lights}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_214.geometry}
          material={materials.default_grey}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_215.geometry}
          material={materials.default_white_2}
          receiveShadow
        />
      </group>
      <group rotation={[0, 0, -Math.PI / 2]}>
        <mesh
          castShadow
          geometry={nodes.Object_217.geometry}
          material={materials.default_white}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_218.geometry}
          material={materials.lights}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_219.geometry}
          material={materials.default_grey}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_220.geometry}
          material={materials.default_white_2}
          receiveShadow
        />
      </group>
      <group rotation={[0, 0, Math.PI / 3]}>
        <mesh
          castShadow
          geometry={nodes.Object_222.geometry}
          material={materials.default_white}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_223.geometry}
          material={materials.lights}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_224.geometry}
          material={materials.default_grey}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_225.geometry}
          material={materials.default_white_2}
          receiveShadow
        />
      </group>
      <group rotation={[0, 0, Math.PI / 6]}>
        <mesh
          castShadow
          geometry={nodes.Object_227.geometry}
          material={materials.default_white}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_228.geometry}
          material={materials.lights}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_229.geometry}
          material={materials.default_grey}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_230.geometry}
          material={materials.default_white_2}
          receiveShadow
        />
      </group>
      <group rotation={[0, 0, 2.094]}>
        <mesh
          castShadow
          geometry={nodes.Object_232.geometry}
          material={materials.default_white}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_233.geometry}
          material={materials.lights}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_234.geometry}
          material={materials.default_grey}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_235.geometry}
          material={materials.default_white_2}
          receiveShadow
        />
      </group>
      <group rotation={[0, 0, Math.PI / 2]}>
        <mesh
          castShadow
          geometry={nodes.Object_237.geometry}
          material={materials.default_white}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_238.geometry}
          material={materials.lights}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_239.geometry}
          material={materials.default_grey}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_240.geometry}
          material={materials.default_white_2}
          receiveShadow
        />
      </group>
      <group rotation={[0, 0, -2.094]}>
        <mesh
          castShadow
          geometry={nodes.Object_242.geometry}
          material={materials.default_white}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_243.geometry}
          material={materials.lights}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_244.geometry}
          material={materials.default_grey}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_245.geometry}
          material={materials.default_white_2}
          receiveShadow
        />
      </group>
      <group rotation={[0, 0, -2.618]}>
        <mesh
          castShadow
          geometry={nodes.Object_247.geometry}
          material={materials.default_white}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_248.geometry}
          material={materials.lights}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_249.geometry}
          material={materials.default_grey}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_250.geometry}
          material={materials.default_white_2}
          receiveShadow
        />
      </group>
      <group
        position={[0, 0, 0.354]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.989}
      >
        <mesh
          castShadow
          geometry={nodes.Object_76.geometry}
          material={materials.default_white}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_77.geometry}
          material={materials.default_white_2}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_78.geometry}
          material={materials.default_white_3}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_79.geometry}
          material={materials.silver_grey}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_80.geometry}
          material={materials.lights}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_81.geometry}
          material={materials.default_grey}
          receiveShadow
        />
      </group>
      <group
        position={[0.387, 0, 0]}
        rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        scale={1.018}
      >
        <mesh
          castShadow
          geometry={nodes.Object_89.geometry}
          material={materials.default_white}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_90.geometry}
          material={materials.silver_grey}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_91.geometry}
          material={materials.lights}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_92.geometry}
          material={materials.default_grey}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_93.geometry}
          material={materials.default_white_2}
          receiveShadow
        />
      </group>
      <group
        position={[0, 0, -0.421]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.834}
      >
        <mesh
          castShadow
          geometry={nodes.Object_95.geometry}
          material={materials.default_white}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_96.geometry}
          material={materials.silver_grey}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_97.geometry}
          material={materials.lights}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_98.geometry}
          material={materials.default_grey}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_99.geometry}
          material={materials.default_white_2}
          receiveShadow
        />
      </group>
      <group
        position={[0, 0.251, 0]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.964}
      >
        <mesh
          castShadow
          geometry={nodes.Object_101.geometry}
          material={materials.default_white}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_102.geometry}
          material={materials.silver_grey}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_103.geometry}
          material={materials.lights}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_104.geometry}
          material={materials.default_grey}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_105.geometry}
          material={materials.default_white_2}
          receiveShadow
        />
      </group>
      <group
        position={[0, -0.298, 0]}
        rotation={[-Math.PI, Math.PI / 2, 0]}
        scale={1.003}
      >
        <mesh
          castShadow
          geometry={nodes.Object_83.geometry}
          material={materials.default_white}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_84.geometry}
          material={materials.silver_grey}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_85.geometry}
          material={materials.lights}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_86.geometry}
          material={materials.default_grey}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_87.geometry}
          material={materials.default_white_2}
          receiveShadow
        />
      </group>
      <group
        position={[0, 0, -0.616]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
        scale={[1, 0.91, 1]}
      >
        <mesh
          castShadow
          geometry={nodes.Object_112.geometry}
          material={materials.default_white}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_113.geometry}
          material={materials.default_white_2}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_114.geometry}
          material={materials.default_white_3}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_115.geometry}
          material={materials.default_grey}
          receiveShadow
        />
      </group>
      <group
        position={[0, 0, -0.616]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[1, 0.91, 1]}
      >
        <mesh
          castShadow
          geometry={nodes.Object_117.geometry}
          material={materials.default_white}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_118.geometry}
          material={materials.default_white_2}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_119.geometry}
          material={materials.default_white_3}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_120.geometry}
          material={materials.default_grey}
          receiveShadow
        />
      </group>
      <group
        position={[0, 0, -0.616]}
        rotation={[Math.PI / 2, Math.PI / 2, 0]}
        scale={[1, 0.91, 1]}
      >
        <mesh
          castShadow
          geometry={nodes.Object_122.geometry}
          material={materials.default_white}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_123.geometry}
          material={materials.default_white_2}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_124.geometry}
          material={materials.default_white_3}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_125.geometry}
          material={materials.default_grey}
          receiveShadow
        />
      </group>
      <group
        position={[0, 0, -0.616]}
        rotation={[Math.PI / 2, Math.PI / 3, 0]}
        scale={[1, 0.91, 1]}
      >
        <mesh
          castShadow
          geometry={nodes.Object_127.geometry}
          material={materials.default_white}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_128.geometry}
          material={materials.default_white_2}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_129.geometry}
          material={materials.default_white_3}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_130.geometry}
          material={materials.default_grey}
          receiveShadow
        />
      </group>
      <group
        position={[0, 0, -0.616]}
        rotation={[-Math.PI / 2, Math.PI / 3, Math.PI]}
        scale={[1, 0.91, 1]}
      >
        <mesh
          castShadow
          geometry={nodes.Object_132.geometry}
          material={materials.default_white}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_133.geometry}
          material={materials.default_white_2}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_134.geometry}
          material={materials.default_white_3}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_135.geometry}
          material={materials.default_grey}
          receiveShadow
        />
      </group>
      <group
        position={[0, 0, -0.616]}
        rotation={[Math.PI / 2, -Math.PI / 3, 0]}
        scale={[1, 0.91, 1]}
      >
        <mesh
          castShadow
          geometry={nodes.Object_137.geometry}
          material={materials.default_white}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_138.geometry}
          material={materials.default_white_2}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_139.geometry}
          material={materials.default_white_3}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_140.geometry}
          material={materials.default_grey}
          receiveShadow
        />
      </group>
      <group
        position={[0, 0, -0.616]}
        rotation={[-Math.PI / 2, -Math.PI / 3, -Math.PI]}
        scale={[1, 0.91, 1]}
      >
        <mesh
          castShadow
          geometry={nodes.Object_142.geometry}
          material={materials.default_white}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_143.geometry}
          material={materials.default_white_2}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_144.geometry}
          material={materials.default_white_3}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_145.geometry}
          material={materials.default_grey}
          receiveShadow
        />
      </group>
      <group
        position={[0, 0, -0.616]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[1, 0.91, 1]}
      >
        <mesh
          castShadow
          geometry={nodes.Object_107.geometry}
          material={materials.default_white}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_108.geometry}
          material={materials.default_white_2}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_109.geometry}
          material={materials.default_white_3}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_110.geometry}
          material={materials.default_grey}
          receiveShadow
        />
      </group>
      <group
        position={[0, 0, -0.616]}
        rotation={[Math.PI / 2, -Math.PI / 6, 0]}
      >
        <mesh
          castShadow
          geometry={nodes.Object_153.geometry}
          material={materials.default_white}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_154.geometry}
          material={materials.default_white_3}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_155.geometry}
          material={materials.default_white_2}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_156.geometry}
          material={materials.default_grey}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_157.geometry}
          material={materials.engine_light}
          receiveShadow
        />
      </group>
      <group
        position={[0, 0, -0.616]}
        rotation={[-Math.PI / 2, -Math.PI / 6, -Math.PI]}
      >
        <mesh
          castShadow
          geometry={nodes.Object_159.geometry}
          material={materials.default_white}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_160.geometry}
          material={materials.default_white_3}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_161.geometry}
          material={materials.default_white_2}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_162.geometry}
          material={materials.default_grey}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_163.geometry}
          material={materials.engine_light}
          receiveShadow
        />
      </group>
      <group position={[0, 0, -0.616]} rotation={[Math.PI / 2, Math.PI / 6, 0]}>
        <mesh
          castShadow
          geometry={nodes.Object_147.geometry}
          material={materials.default_white}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_148.geometry}
          material={materials.default_white_3}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_149.geometry}
          material={materials.default_white_2}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_150.geometry}
          material={materials.default_grey}
          receiveShadow
        />
        <mesh
          castShadow
          geometry={nodes.Object_151.geometry}
          material={materials.engine_light}
          receiveShadow
        />
      </group>
      <mesh
        castShadow
        geometry={nodes.Object_192.geometry}
        material={materials.default_white}
        receiveShadow
      />
      <mesh
        castShadow
        geometry={nodes.Object_193.geometry}
        material={materials.lights}
        receiveShadow
      />
      <mesh
        castShadow
        geometry={nodes.Object_194.geometry}
        material={materials.default_grey}
        receiveShadow
      />
      <mesh
        castShadow
        geometry={nodes.Object_195.geometry}
        material={materials.default_white_2}
        receiveShadow
      />
      <mesh
        castShadow
        geometry={nodes.Object_252.geometry}
        material={materials.material_0}
        position={[0, 3.109, 0]}
        receiveShadow
        rotation={[-Math.PI, 0, 0]}
        scale={0.211}
      />
      <mesh
        castShadow
        geometry={nodes.Object_171.geometry}
        material={materials.default_white}
        receiveShadow
      />
      <mesh
        castShadow
        geometry={nodes.Object_172.geometry}
        material={materials.default_grey}
        receiveShadow
      />
      <mesh
        castShadow
        geometry={nodes.Object_173.geometry}
        material={materials.lights}
        receiveShadow
      />
      <group position={[0, 4.091, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, -0.416, 0]} scale={[2.292, 1, 4.422]}>
            <group position={[0, 0.429, 0]} scale={[0.436, 1, 0.226]}>
              <mesh
                castShadow
                geometry={nodes.Object_5.geometry}
                material={materials["default_white_2.001"]}
                receiveShadow
              />
              <mesh
                castShadow
                geometry={nodes.Object_6001.geometry}
                material={materials["silver_grey.001"]}
                receiveShadow
              />
              <mesh
                castShadow
                geometry={nodes.Object_7.geometry}
                material={materials["default_grey.001"]}
                receiveShadow
              />
            </group>
            <group
              position={[0, -0.226, 0]}
              rotation={[-Math.PI, 0, 0]}
              scale={[0.436, 1, 0.226]}
            >
              <mesh
                castShadow
                geometry={nodes.Object_10001.geometry}
                material={materials["silver_grey.001"]}
                receiveShadow
              />
              <mesh
                castShadow
                geometry={nodes.Object_11.geometry}
                material={materials["default_grey.001"]}
                receiveShadow
              />
              <mesh
                castShadow
                geometry={nodes.Object_9.geometry}
                material={materials["default_white_2.001"]}
                receiveShadow
              />
            </group>
            <group position={[0, 0.416, -0.187]} scale={[0.436, 1, 0.905]}>
              <mesh
                castShadow
                geometry={nodes.Object_20.geometry}
                material={materials["default_white_2.001"]}
                receiveShadow
              />
              <mesh
                castShadow
                geometry={nodes.Object_21.geometry}
                material={materials.ENGING_light}
                receiveShadow
              />
            </group>
            <group position={[0, 0.416, -0.187]} scale={[0.436, 1, 0.905]}>
              <mesh
                castShadow
                geometry={nodes.Object_13.geometry}
                material={materials["default_white.001"]}
                receiveShadow
              />
              <mesh
                castShadow
                geometry={nodes.Object_14001.geometry}
                material={materials["default_white_2.001"]}
                receiveShadow
              />
              <mesh
                castShadow
                geometry={nodes.Object_15.geometry}
                material={materials["default_grey.001"]}
                receiveShadow
              />
              <mesh
                castShadow
                geometry={nodes.Object_16.geometry}
                material={materials["default_white_3.001"]}
                receiveShadow
              />
              <mesh
                castShadow
                geometry={nodes.Object_17.geometry}
                material={materials["Material.001"]}
                receiveShadow
              />
              <mesh
                castShadow
                geometry={nodes.Object_18001.geometry}
                material={materials.heat_sheild}
                receiveShadow
              />
            </group>
          </group>
        </group>
      </group>
      <group position={[-1.442, 0, 4.28]} rotation={[-1.571, -1.566, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0.428, 1.369]} scale={[2.242, 1, 5.943]}>
            <group position={[0, 0.215, -0.85]} scale={[0.446, 1, 0.168]}>
              <mesh
                castShadow
                geometry={nodes.Object_5001.geometry}
                material={materials["default_white_2.002"]}
                receiveShadow
              />
              <mesh
                castShadow
                geometry={nodes.Object_6002.geometry}
                material={materials["silver_grey.002"]}
                receiveShadow
              />
              <mesh
                castShadow
                geometry={nodes.Object_7001.geometry}
                material={materials["default_grey.002"]}
                receiveShadow
              />
            </group>
            <group
              position={[0.516, 0.159, -0.783]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.25, 0.145, 0.251]}
            >
              <mesh
                castShadow
                geometry={nodes.Object_19.geometry}
                material={materials["default_grey.002"]}
                receiveShadow
              />
              <mesh
                castShadow
                geometry={nodes.Object_20001.geometry}
                material={materials["ENGING_light.001"]}
                receiveShadow
              />
            </group>
            <group position={[0, -0.428, -0.23]} scale={[0.638, 1.43, 0.241]}>
              <mesh
                castShadow
                geometry={nodes.Object_10002.geometry}
                material={materials["default_grey.003"]}
                receiveShadow
              />
              <mesh
                castShadow
                geometry={nodes.Object_11001.geometry}
                material={materials["Material.002"]}
                receiveShadow
              />
              <mesh
                castShadow
                geometry={nodes.Object_12.geometry}
                material={materials["heat_sheild.001"]}
                receiveShadow
              />
              <mesh
                castShadow
                geometry={nodes.Object_13001.geometry}
                material={materials["default_white_2.002"]}
                receiveShadow
              />
              <mesh
                castShadow
                geometry={nodes.Object_14002.geometry}
                material={materials["default_white_3.002"]}
                receiveShadow
              />
              <mesh
                castShadow
                geometry={nodes.Object_15001.geometry}
                material={materials.very_white}
                receiveShadow
              />
              <mesh
                castShadow
                geometry={nodes.Object_9001.geometry}
                material={materials["default_white.002"]}
                receiveShadow
              />
            </group>
            <mesh
              castShadow
              geometry={nodes.Object_17001.geometry}
              material={materials["material_0.001"]}
              position={[0, -0.428, -0.23]}
              receiveShadow
              scale={[0.638, 1.43, 0.241]}
            />
            <mesh
              castShadow
              geometry={nodes.Object_22001.geometry}
              material={materials["heat_sheild.002"]}
              position={[0.43, 0.802, -0.543]}
              receiveShadow
              scale={[0.446, 1, 0.077]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/endurance.glb");
