/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as ShadersRouteImport } from './routes/shaders'
import { Route as AdminRouteRouteImport } from './routes/admin.route'
import { Route as AppRouteRouteImport } from './routes/_app.route'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminPostsRouteImport } from './routes/admin.posts'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AppPlaygroundRouteImport } from './routes/_app.playground'
import { Route as AppPostsRouteRouteImport } from './routes/_app.posts.route'
import { Route as AppPostsIndexRouteImport } from './routes/_app.posts.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as AppPostsSlugRouteImport } from './routes/_app.posts.$slug'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ShadersRoute = ShadersRouteImport.update({
  id: '/shaders',
  path: '/shaders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppPlaygroundRoute = AppPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPostsRouteRoute = AppPostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPostsIndexRoute = AppPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPostsRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPostsSlugRoute = AppPostsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppPostsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/shaders': typeof ShadersRoute
  '/test': typeof TestRoute
  '/posts': typeof AppPostsRouteRouteWithChildren
  '/playground': typeof AppPlaygroundRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/posts/$slug': typeof AppPostsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/posts/': typeof AppPostsIndexRoute
}
export interface FileRoutesByTo {
  '/shaders': typeof ShadersRoute
  '/test': typeof TestRoute
  '/playground': typeof AppPlaygroundRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/posts/$slug': typeof AppPostsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/posts': typeof AppPostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/shaders': typeof ShadersRoute
  '/test': typeof TestRoute
  '/_app/posts': typeof AppPostsRouteRouteWithChildren
  '/_app/playground': typeof AppPlaygroundRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/posts/$slug': typeof AppPostsSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/posts/': typeof AppPostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/shaders'
    | '/test'
    | '/posts'
    | '/playground'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/posts'
    | '/admin/projects'
    | '/'
    | '/admin/'
    | '/posts/$slug'
    | '/api/auth/$'
    | '/posts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/shaders'
    | '/test'
    | '/playground'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/posts'
    | '/admin/projects'
    | '/'
    | '/admin'
    | '/posts/$slug'
    | '/api/auth/$'
    | '/posts'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/shaders'
    | '/test'
    | '/_app/posts'
    | '/_app/playground'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/posts'
    | '/admin/projects'
    | '/_app/'
    | '/admin/'
    | '/_app/posts/$slug'
    | '/api/auth/$'
    | '/_app/posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ShadersRoute: typeof ShadersRoute
  TestRoute: typeof TestRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shaders': {
      id: '/shaders'
      path: '/shaders'
      fullPath: '/shaders'
      preLoaderRoute: typeof ShadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_app/playground': {
      id: '/_app/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof AppPlaygroundRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/posts': {
      id: '/_app/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AppPostsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/posts/': {
      id: '/_app/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof AppPostsIndexRouteImport
      parentRoute: typeof AppPostsRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/posts/$slug': {
      id: '/_app/posts/$slug'
      path: '/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof AppPostsSlugRouteImport
      parentRoute: typeof AppPostsRouteRoute
    }
  }
}

interface AppPostsRouteRouteChildren {
  AppPostsSlugRoute: typeof AppPostsSlugRoute
  AppPostsIndexRoute: typeof AppPostsIndexRoute
}

const AppPostsRouteRouteChildren: AppPostsRouteRouteChildren = {
  AppPostsSlugRoute: AppPostsSlugRoute,
  AppPostsIndexRoute: AppPostsIndexRoute,
}

const AppPostsRouteRouteWithChildren = AppPostsRouteRoute._addFileChildren(
  AppPostsRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppPostsRouteRoute: typeof AppPostsRouteRouteWithChildren
  AppPlaygroundRoute: typeof AppPlaygroundRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppPostsRouteRoute: AppPostsRouteRouteWithChildren,
  AppPlaygroundRoute: AppPlaygroundRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ShadersRoute: ShadersRoute,
  TestRoute: TestRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
